spring.application.name=Child

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.messages.basename=messages
spring.messages.encoding=UTF-8
#vm???? ????.???? ?? -D
#spring.profiles.active=dev
spring.profiles.active=oracle, dev
#SQL ?? ????.
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.servlet.session.timeout=24h
# ?? ?? ??
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.forward-headers-strategy=framework
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

server.servlet.session.persistent=false
server.servlet.session.cookie.same-site=lax
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG